# Generated by Django 4.0 on 2022-01-01 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='user',
            new_name='userbuyer',
        ),
    ]
